#if UNITY_EDITOR

using System.Collections.Generic;
using System.IO;
using System.Text;
using BehaviourTree.Core;
using UnityEditor;
using UnityEngine;

namespace BehaviourTree.Editor
{
    public static class NodeFieldBindingGenerator
    {
        private const string FilePath = "Assets/Scripts/BehaviourTree/Runtime/Execution/Generated/NodeFieldBindings.cs";

        [MenuItem("BehaviourTree/Generate Node Field Bindings", priority = 30)]
        public static void Generate()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════════");
            sb.AppendLine("// AUTO-GENERATED by NodeFieldBindingGenerator. Do not edit manually.");
            sb.AppendLine("// Regenerate via Tools → BehaviourTree → Generate Node Field Bindings.");
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using BehaviourTree;");
            sb.AppendLine("using BehaviourTree.Core;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace BehaviourTree.Runtime");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class NodeFieldBindings");
            sb.AppendLine("    {");

            var allParams = MethodMetadataCache.Cache;

            foreach (var kvp in allParams)
            {
                MethodID methodId = kvp.Key;
                List<ParamInfo> fields = kvp.Value;

                if (fields == null || fields.Count == 0) continue;
                if (!MethodMetadataCache.ShouldGenerateBindings(methodId)) continue;

                string structName = methodId.ToString() + "_NodeFields";
                string methodName = methodId.ToString();

                sb.AppendLine($"        public static {structName} Deserialize{methodName}(ReadOnlySpan<FieldData> fields, BlackBoard blackboard)");
                sb.AppendLine("        {");
                sb.AppendLine("            FieldReader reader = new FieldReader(fields, blackboard);");
                sb.AppendLine($"            return new {structName}");
                sb.AppendLine("            {");

                for (int i = 0; i < fields.Count; i++)
                {
                    ParamInfo info = fields[i];
                    string readerCall = GetReaderCall(info.fieldType, info.index);
                    string comment = $"index {info.index}: {info.fieldName}" +
                                     (info.isVariable ? " (blackboard variable)" : " (constant)");

                    sb.AppendLine($"                // {comment}");
                    sb.AppendLine($"                {info.fieldName} = {readerCall},");
                }

                sb.AppendLine("            };");
                sb.AppendLine("        }");
                sb.AppendLine();

                bool hasVars = fields.Exists(f => f.isVariable);
                if (hasVars)
                {
                    sb.AppendLine($"        public static void Serialize{methodName}({structName} p, ReadOnlySpan<FieldData> fields, BlackBoard blackboard)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            FieldReader writer = new FieldReader(fields, blackboard);");

                    for (int i = 0; i < fields.Count; i++)
                    {
                        ParamInfo info = fields[i];
                        if (!info.isVariable) continue;

                        string writerCall = GetWriterCall(info.fieldType, info.index, info.fieldName);
                        sb.AppendLine($"            {writerCall}");
                    }

                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            string newContent = sb.ToString();

            if (File.Exists(FilePath))
            {
                string existing = File.ReadAllText(FilePath);
                if (existing == newContent)
                    return;
            }

            string dir = Path.GetDirectoryName(FilePath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(FilePath, newContent);
            AssetDatabase.ImportAsset(FilePath);
            Debug.Log("NodeFieldBindings regenerated at: " + FilePath);
        }

        private static string GetReaderCall(System.Type fieldType, int index)
        {
            if (fieldType != null && fieldType.IsEnum)
                return $"reader.GetEnum<{GetTypeNameForCode(fieldType)}>({index})";
            if (fieldType == typeof(int))
                return $"reader.GetInt({index})";
            if (fieldType == typeof(float))
                return $"reader.GetFloat({index})";
            if (fieldType == typeof(bool))
                return $"reader.GetBool({index})";
            if (fieldType == typeof(Vector2))
                return $"reader.GetVector2({index})";
            if (fieldType == typeof(Vector3))
                return $"reader.GetVector3({index})";
            if (fieldType == typeof(GameObject))
                return $"reader.GetGameObject({index})";
            if (fieldType == typeof(Transform))
                return $"reader.GetTransform({index})";

            Debug.LogWarning($"[NodeFieldBindingGenerator] Unsupported type {fieldType.FullName} — defaulting to GetInt({index})");
            return $"reader.GetInt({index})";
        }

        private static string GetWriterCall(System.Type fieldType, int index, string fieldName)
        {
            string access = $"p.{fieldName}";
            if (fieldType != null && fieldType.IsEnum)
                return $"writer.SetEnum({index}, {access});";
            if (fieldType == typeof(int))
                return $"writer.SetInt({index}, {access});";
            if (fieldType == typeof(float))
                return $"writer.SetFloat({index}, {access});";
            if (fieldType == typeof(bool))
                return $"writer.SetBool({index}, {access});";
            if (fieldType == typeof(Vector2))
                return $"writer.SetVector2({index}, {access});";
            if (fieldType == typeof(Vector3))
                return $"writer.SetVector3({index}, {access});";
            if (fieldType == typeof(GameObject))
                return $"writer.SetGameObject({index}, {access});";
            if (fieldType == typeof(Transform))
                return $"writer.SetTransform({index}, {access});";

            Debug.LogWarning($"[NodeFieldBindingGenerator] Unsupported type {fieldType.FullName} — defaulting to SetInt({index}, {access})");
            return $"writer.SetInt({index}, {access});";
        }

        private static string GetTypeNameForCode(System.Type type)
        {
            string fullName = type.FullName.Replace("+", ".");
            return "global::" + fullName;
        }
    }
}

#endif
