using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using BehaviourTree.Core;
using BehaviourTree.Runtime;
using UnityEditor;
using UnityEngine;

namespace BehaviourTree.EditorTools.Codegen
{
    /// <summary>
    /// Scans all NodeMethod types (via MethodRegistry, the single source of field
    /// selection) and writes GeneratedBindingAccessors.cs into
    /// Assets/BehaviourTree/Generated/. Run manually from the menu, or let the
    /// editor staleness warning remind you after changing method fields.
    /// </summary>
    public static class BindingAccessorGenerator
    {
        public const string OutputFolder = "Assets/BehaviourTree/Generated";
        public const string OutputFile = OutputFolder + "/GeneratedBindingAccessors.cs";

        // NOTE: deliberately NO asmdef in the output folder. The generated code must
        // reference types from ALL assemblies (NodeMethod types in asmdefs AND gameplay
        // components like HealthComponent in Assembly-CSharp) — only Assembly-CSharp
        // can see everything (it auto-references all asmdefs).

        [MenuItem("Behaviour Tree/Generate Binding Accessors")]
        public static void Generate()
        {
            var methodFields = new List<(Type type, FieldInfo[] fields)>();

            foreach (string methodName in MethodRegistry.GetMethodNames())
            {
                Type type = MethodRegistry.GetMethodType(methodName);
                if (type == null) continue;

                FieldBinding[] bindings = MethodRegistry.CreateBindings(type);
                if (bindings == null || bindings.Length == 0) continue;

                var fields = new List<FieldInfo>(bindings.Length);
                foreach (FieldBinding b in bindings)
                    if (b?.fieldInfo != null)
                        fields.Add(b.fieldInfo);

                if (fields.Count > 0)
                    methodFields.Add((type, fields.ToArray()));
            }

            // Stable order → stable diffs in the generated file.
            methodFields.Sort((a, b) => string.CompareOrdinal(a.type.FullName, b.type.FullName));

            // Tracked bindings: opt-in via [GenerateBindingAccessors] on the component.
            var tracked = new List<(Type type, MemberInfo member)>();
            foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                Type[] types;
                try { types = assembly.GetTypes(); }
                catch (ReflectionTypeLoadException e) { types = e.Types; }

                foreach (Type t in types)
                {
                    if (t == null || !typeof(Component).IsAssignableFrom(t)) continue;
                    if (t.GetCustomAttribute<GenerateBindingAccessorsAttribute>() == null) continue;

                    const BindingFlags Flags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly;
                    foreach (FieldInfo f in t.GetFields(Flags))
                        tracked.Add((t, f));
                    foreach (PropertyInfo p in t.GetProperties(Flags))
                        if (p.CanRead && p.GetIndexParameters().Length == 0)
                            tracked.Add((t, p));
                }
            }

            tracked.Sort((a, b) => string.CompareOrdinal(a.type.FullName + "." + a.member.Name,
                                                          b.type.FullName + "." + b.member.Name));

            Directory.CreateDirectory(OutputFolder);

            string content = BuildFile(methodFields, tracked);
            if (File.Exists(OutputFile) && File.ReadAllText(OutputFile) == content)
            {
                Debug.Log($"[BindingAccessorGenerator] Unchanged ({methodFields.Count} method types) — no rewrite.");
                return;
            }

            File.WriteAllText(OutputFile, content);
            AssetDatabase.Refresh();

            Debug.Log($"[BindingAccessorGenerator] Wrote {OutputFile} ({methodFields.Count} method types, {tracked.Count} tracked members).");
        }

        /// <summary>Pure file builder — unit-testable without touching the asset DB.</summary>
        public static string BuildFile(IReadOnlyList<(Type type, FieldInfo[] fields)> methodFields,
            IReadOnlyList<(Type type, MemberInfo member)> trackedMembers = null)
        {
            var sb = new StringBuilder(8192);
            sb.Append("// <auto-generated/> by BindingAccessorGenerator — do not edit. Regenerate via 'Behaviour Tree/Generate Binding Accessors'.\n");
            sb.Append("#pragma warning disable\n");
            sb.Append("using System;\n");
            sb.Append("using BehaviourTree.Core;\n");
            sb.Append("using UnityEngine;\n\n");
            sb.Append("namespace BehaviourTree.Generated\n{\n");
            sb.Append("    public static class GeneratedBindingAccessors\n    {\n");
            sb.Append("        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]\n");
            sb.Append("        public static void RegisterAll()\n        {\n");
            sb.Append("            GeneratedAccessorRegistry.Clear();\n");

            foreach ((Type type, FieldInfo[] fields) in methodFields)
            {
                foreach (FieldInfo field in fields)
                {
                    string registration = AccessorEmitter.EmitRegistration(type, field);
                    if (registration != null)
                        sb.Append(registration);
                }
            }

            sb.Append("            TrackedAccessorRegistry.Clear();\n");
            if (trackedMembers != null)
            {
                foreach ((Type type, MemberInfo member) in trackedMembers)
                {
                    string registration = AccessorEmitter.EmitTrackedRegistration(type, member);
                    if (registration != null)
                        sb.Append(registration);
                }
            }

            sb.Append("        }\n\n");
            sb.Append("        private static void R(Type methodType, string fieldName, Type fieldType,\n");
            sb.Append("            GeneratedAccessorRegistry.ReadAccessor read, GeneratedAccessorRegistry.WriteAccessor write)\n");
            sb.Append("            => GeneratedAccessorRegistry.Register(methodType, fieldName, fieldType, read, write);\n\n");
            sb.Append("        private static void TR(Type compType, string memberName, Type memberType,\n");
            sb.Append("            TrackedAccessorRegistry.PushAccessor push)\n");
            sb.Append("            => TrackedAccessorRegistry.Register(compType, memberName, memberType, push);\n");
            sb.Append("    }\n}\n");
            return sb.ToString();
        }
    }
}
