using System.Reflection;
using BehaviourTree.Core;
using BehaviourTree.EditorTools.Codegen;
using BehaviourTree.Runtime;
using NUnit.Framework;

namespace BehaviourTree.Tests
{
    public class BindingAccessorGeneratorTests
    {
        private class GenStubMethod : ActionMethod
        {
            public float speed;
            public override NodeState Execute(Runtime.TickContext ctx) => NodeState.SUCCESS;
        }

        [Test]
        public void BuildFile_ContainsRegisterAll_AndAccessor()
        {
            var fields = typeof(GenStubMethod).GetFields(BindingFlags.Public | BindingFlags.Instance);
            string file = BindingAccessorGenerator.BuildFile(
                new[] { (typeof(GenStubMethod), fields) });

            StringAssert.Contains("// <auto-generated/>", file);
            StringAssert.Contains("namespace BehaviourTree.Generated", file);
            StringAssert.Contains("public static class GeneratedBindingAccessors", file);
            StringAssert.Contains("RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)", file);
            StringAssert.Contains("GeneratedAccessorRegistry.Clear();", file);
            StringAssert.Contains("bb.GetFloat(slot)", file);
            StringAssert.Contains("GenStubMethod", file);
        }

        [Test]
        public void IsTestAssembly_FlagsTestAssemblies_NotGameAssemblies()
        {
            Assert.IsTrue(BindingAccessorGenerator.IsTestAssembly(typeof(BindingAccessorGeneratorTests).Assembly));
            Assert.IsFalse(BindingAccessorGenerator.IsTestAssembly(typeof(BlackBoard).Assembly));      // BehaviourTree.Core
            Assert.IsFalse(BindingAccessorGenerator.IsTestAssembly(typeof(MethodRegistry).Assembly));  // BehaviourTree.Runtime
        }
    }
}
