#if UNITY_EDITOR

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using BehaviourTree.Core;
using UnityEditor;
using UnityEngine;

namespace BehaviourTree.Editor
{
    /// <summary>
    /// Scans all BlackboardDefinition assets and regenerates <c>BlackboardEnums.cs</c>
    /// with one enum per definition for zero-cost typed blackboard access.
    /// </summary>
    public static class BlackboardEnumGenerator
    {
        private const string FilePath = "Assets/Scripts/BehaviourTree/Runtime/Execution/Generated/BlackboardEnums.cs";

        //[MenuItem("BehaviourTree/Generate/Generate Blackboard Key Enums", priority = 31)]
        public static void Generate()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════════");
            sb.AppendLine("// AUTO-GENERATED by BlackboardEnumGenerator. Do not edit manually.");
            sb.AppendLine("// Regenerate via Tools → BehaviourTree → Generate Blackboard Enums.");
            sb.AppendLine("// ═══════════════════════════════════════════════════════════════════");
            sb.AppendLine();
            sb.AppendLine("namespace BehaviourTree.Runtime");
            sb.AppendLine("{");

            var definitions = FindAllDefinitions();
            var usedEnumNames = new HashSet<string>();

            foreach (var def in definitions)
            {
                if (def == null || def.VariableCount == 0)
                    continue;

                string rawName = def.name;
                // Strip trailing _BB_Definition if present
                if (rawName.EndsWith("_BB_Definition"))
                    rawName = rawName.Substring(0, rawName.Length - "_BB_Definition".Length);

                string enumName = SanitizeIdentifier(rawName) + "_BB_Keys";

                // Deduplicate
                string uniqueName = enumName;
                int suffix = 1;
                while (!usedEnumNames.Add(uniqueName))
                {
                    uniqueName = enumName + "_" + suffix;
                    suffix++;
                }

                sb.AppendLine($"    public enum {uniqueName} : int");
                sb.AppendLine("    {");

                int[] slotOffsets = ComputeSlotOffsets(def);

                IReadOnlyList<BlackboardVariableBase> allVars = def.GetAllVariables();
                for (int i = 0; i < allVars.Count; i++)
                {
                    BlackboardVariableBase variable = allVars[i];
                    string varName = SanitizeIdentifier(variable.Name);
                    if (string.IsNullOrEmpty(varName))
                        varName = $"Var_{i}";
                    if (char.IsDigit(varName[0]))
                        varName = "_" + varName;

                    int stride = variable.Stride;
                    int effectiveStride = (stride > 1) ? stride : 1;

                    // Resolve type for comment
                    string typeComment = "";
                    if (FieldTypeHelper.TryGetSystemTypeFromName(variable.TypeName, out Type resolvedType) && resolvedType != null)
                        typeComment = $" // type: {resolvedType.Name}";

                    if (effectiveStride > 1)
                    {
                        sb.AppendLine($"        // Slots {slotOffsets[i]}..{slotOffsets[i] + effectiveStride - 1} (stride={effectiveStride}){typeComment}");
                    }

                    sb.AppendLine($"        {varName} = {slotOffsets[i]}{(i < allVars.Count - 1 ? "," : "")}{(effectiveStride == 1 ? typeComment : "")}");
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");

            string newContent = sb.ToString();

            if (File.Exists(FilePath))
            {
                string existing = File.ReadAllText(FilePath);
                if (existing == newContent)
                    return;
            }

            string dir = Path.GetDirectoryName(FilePath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(FilePath, newContent);
            AssetDatabase.ImportAsset(FilePath);
            Debug.Log("BlackboardEnums regenerated at: " + FilePath);
        }

        private static List<BlackboardDefinition> FindAllDefinitions()
        {
            List<BlackboardDefinition> results = new List<BlackboardDefinition>();
            string[] guids = AssetDatabase.FindAssets("t:BlackboardDefinition");
            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                BlackboardDefinition asset = AssetDatabase.LoadAssetAtPath<BlackboardDefinition>(path);
                if (asset != null)
                    results.Add(asset);
            }
            return results;
        }

        /// <summary>
        /// Computes the slot offset for each variable in a definition,
        /// accounting for stride. Returns an array where index[v] = slot offset.
        /// </summary>
        private static int[] ComputeSlotOffsets(BlackboardDefinition def)
        {
            IReadOnlyList<BlackboardVariableBase> allVars = def.GetAllVariables();
            int[] offsets = new int[allVars.Count];
            int currentSlot = 0;

            for (int i = 0; i < allVars.Count; i++)
            {
                offsets[i] = currentSlot;
                int stride = allVars[i].Stride;
                currentSlot += (stride > 1) ? stride : 1;
            }

            return offsets;
        }

        /// <summary>
        /// Replaces any character that is not a letter, digit, or underscore with an underscore.
        /// </summary>
        private static string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name))
                return name;
            return Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");
        }
    }
}

#endif
