namespace BehaviourTree.Core
{
    public enum MethodID 
    {
        NONE = 0,
        [MethodCategory(BehaviourNodeType.ACTION)]HELLOWORLD = 1,
        [MethodCategory(BehaviourNodeType.ACTION)]BYEWORLD = 2,
        [MethodCategory(BehaviourNodeType.CONDITION)]WAITWORLD = 3,
        [MethodCategory(BehaviourNodeType.DECORATOR)]INVERTER = 4,
        [MethodCategory(BehaviourNodeType.DECORATOR)]REPEATER = 5,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareInt = 6,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareFloat = 7,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareBool = 8,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareVector2 = 9,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareVector3 = 10,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareGameObject = 11,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareTransform = 12,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetInt = 13,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetFloat = 14,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetBool = 15,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetVector2 = 16,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetVector3 = 17,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetGameObject = 18,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetTransform = 19,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearInt = 20,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearFloat = 21,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearBool = 22,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearVector2 = 23,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearVector3 = 24,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearGameObject = 25,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearTransform = 26,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ToggleBool = 27,
        [MethodCategory(BehaviourNodeType.ACTION)]WaitSeconds = 28,
        [MethodCategory(BehaviourNodeType.CONDITION)]Cooldown = 29,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedInt = 30,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedFloat = 31,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedBool = 32,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedVector2 = 33,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedVector3 = 34,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedGameObject = 35,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedTransform = 36,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_EdgeRisingBool = 37,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_EdgeFallingBool = 38,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CheckBool = 39,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CheckGameObject = 40,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CheckTransform = 41,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogInt = 42,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogFloat = 43,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogBool = 44,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogVector2 = 45,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogVector3 = 46,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogGameObject = 47,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogTransform = 48,
    }
}
