namespace BehaviourTree.Core
{
    public enum MethodID 
    {
        NONE = 0,
        [MethodCategory(BehaviourNodeType.DECORATOR)]INVERTER = 1,
        [MethodCategory(BehaviourNodeType.DECORATOR)]REPEATER = 2,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareInt = 3,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareFloat = 4,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareBool = 5,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareVector2 = 6,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareVector3 = 7,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareGameObject = 8,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CompareTransform = 9,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetInt = 10,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetFloat = 11,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetBool = 12,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetVector2 = 13,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetVector3 = 14,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetGameObject = 15,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetTransform = 16,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearInt = 17,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearFloat = 18,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearBool = 19,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearVector2 = 20,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearVector3 = 21,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearGameObject = 22,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ClearTransform = 23,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_ToggleBool = 24,
        [MethodCategory(BehaviourNodeType.ACTION)]WaitSeconds = 25,
        [MethodCategory(BehaviourNodeType.CONDITION)]Cooldown = 26,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedInt = 27,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedFloat = 28,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedBool = 29,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedVector2 = 30,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedVector3 = 31,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedGameObject = 32,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_HasChangedTransform = 33,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_EdgeRisingBool = 34,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_EdgeFallingBool = 35,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CheckBool = 36,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CheckGameObject = 37,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CheckTransform = 38,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogInt = 39,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogFloat = 40,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogBool = 41,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogVector2 = 42,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogVector3 = 43,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogGameObject = 44,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_LogTransform = 45,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CheckVector2 = 46,
        [MethodCategory(BehaviourNodeType.CONDITION)]BB_CheckVector3 = 47,
        #region EnemyMethods
        [MethodCategory(BehaviourNodeType.ACTION)]Enemy_MoveTo = 48,
        [MethodCategory(BehaviourNodeType.ACTION)]Enemy_SelectPatrolPoint = 49,
        [MethodCategory(BehaviourNodeType.ACTION)]Enemy_SelectEngagePosition = 50,
        [MethodCategory(BehaviourNodeType.CONDITION)]Enemy_HasArrived = 51,
        [MethodCategory(BehaviourNodeType.ACTION)]Enemy_StopMovement = 52,
        [MethodCategory(BehaviourNodeType.ACTION)]Enemy_SelectAimTarget = 53,
        [MethodCategory(BehaviourNodeType.ACTION)]Enemy_StartTrajectorySearch = 54,
        [MethodCategory(BehaviourNodeType.CONDITION)]Enemy_IsTrajectoryReady = 55,
        [MethodCategory(BehaviourNodeType.ACTION)]Enemy_SetAiming = 56,
        [MethodCategory(BehaviourNodeType.ACTION)]Enemy_WaitForReload = 57,
        [MethodCategory(BehaviourNodeType.ACTION)]Enemy_Fire = 58,
        [MethodCategory(BehaviourNodeType.CONDITION)]Enemy_IsAimed = 59,
        [MethodCategory(BehaviourNodeType.CONDITION)]Enemy_DetectTarget = 60,
        [MethodCategory(BehaviourNodeType.ACTION)]Enemy_SelectDetectedTarget = 61,
        [MethodCategory(BehaviourNodeType.CONDITION)]Enemy_IsInFiringRange = 62,
        [MethodCategory(BehaviourNodeType.CONDITION)]Enemy_HasLineOfSight = 63,
        [MethodCategory(BehaviourNodeType.ACTION)]Enemy_FireSequence = 64,
        #endregion
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetVector2FromTransform = 65,
        [MethodCategory(BehaviourNodeType.ACTION)]BB_SetVector3FromTransform = 66,
        [MethodCategory(BehaviourNodeType.ACTION)]Enemy_MoveTo_Transform = 67,
    }
}
